# Usando a imagem base do nixpacks
FROM ghcr.io/railwayapp/nixpacks:ubuntu-1727136237

# Definindo o diretório de trabalho
WORKDIR /app/

# Copiando o código da aplicação para dentro do container
COPY . /app/.

# Executando o Maven para construir o projeto
RUN chmod +x ./mvnw && ./mvnw -B -DskipTests clean install

# Expondo a porta que será usada pela aplicação
EXPOSE 8080

# Comando para iniciar a aplicação
CMD ["java", "-jar", "target/seu-projeto.jar"]
