# Primeira etapa: usar Maven para compilar o projeto
FROM maven:3.9.7-amazoncorretto-17 AS build

# Copiar o projeto para o diretório de trabalho dentro do container
COPY . /app

# Definir o diretório de trabalho
WORKDIR /app

# Executar o Maven para limpar e compilar o projeto
RUN ./mvnw clean install

# Segunda etapa: criar a imagem final usando Amazon Corretto
FROM amazoncorretto:17-alpine-jdk

# Copiar o JAR gerado na primeira etapa para o diretório de trabalho da imagem final
COPY --from=build /app/target/agenda-0.0.1-SNAPSHOT.jar /app/app.jar

# Definir o diretório de trabalho
WORKDIR /app

# Expor a porta 8080
EXPOSE 8080

# Comando para rodar o JAR
CMD ["java", "-jar", "app.jar"]
