FROM ghcr.io/railwayapp/nixpacks:ubuntu-1727136237

# Definindo o diretório de trabalho
WORKDIR /app/

# Copiando o código da aplicação para o container
COPY ../../../../../../target /app/.

# Executando o build da aplicação
RUN chmod +x ./mvnw && ./mvnw -B -DskipTests clean install

# Expondo a porta que sua aplicação usa
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "target/seu-projeto.jar"]